# Generated by Django 6.0.6 on 2026-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_options',
            field=models.BooleanField(default=False, help_text='If enabled, the A/B/C/D options within each question are shuffled per student.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='If enabled, each student sees questions in a unique order.'),
        ),
    ]
